### ISSUE TITLE
.scn file from Grandia HD Collection

### ISSUE THREAD

**Issue by costelabr17** [marcussacana/KrKrZSceneManager#2]
i don't know how to do this, but hope you can help. I think your tool can be modded to work with this game in Nintendo Switch Version, i want to translate this game to brazilian portuguese, let me know if you can help me i will let the link to a sample file, thank you anyway.

http://www.mediafire.com/file/07gzjvp1vrh0vqh/3c00.scn/file

**Comment by marcussacana** [comment]
Ele tem a extensão .scn mas é um arquivo completamente diferente em sua estrutura.
Se eu fosse realmente 'adicionar suporte' teria que criar uma ferramenta completamente nova pra esse arquivo.
Infelizmente eu não tenho um Switch para depurar o jogo, meu computador também não aguenta o emulador então é meio complicado pra eu fazer uma ferramenta para switch.

**Comment by costelabr17** [comment]
Entendi eu  precisava era achar um jeito de extrair os textos desses arquivos e reimportar eles eu até consigo editar via hexadecimal ou notepad++, mas se eu trocar algum código do lugar já era tela preta no jogo

**Comment by marcussacana** [comment]
É justamente por coisa assim que se precise ter o jogo em mãos, de preferência no console real invés de emulador, porque emulador muitas vezes funciona com 'hacks' que tentam ignorar os possíveis erros, isso significa que um mod que funciona em um emulador não necessariamente funciona no console real.
De qualquer forma, editar em hexadecimal lhe impede de adicionar ou remover letras nas frases, isso é uma limitação e tanto na hora de traduzir, só estudando o arquivo pra encontrar todas as offsets e poder modificar o tamanho das linhas.
